name: jacoco_coverage
on:
  push:
    branches:
      - master
      - isw2-testing-dev
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
      - name: jacoco-coverage
        run: mvn clean verify -P jacocoProfile -Dsurefire.rerunFailingTestsCount=2
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: tests/target/site/jacoco-aggregate/
          if-no-files-found: error
