
# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches:
    - master
    - isw2-testing-dev
    - isw2-testing

  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version:  8
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install -Dsurefire.rerunFailingTestsCount=2
      - name: Upload surefire report
        uses: actions/upload-artifact@v3
        with:
          name: pit-report
          path: tajo-cluster-tests/target/surefire-reports/
          if-no-files-found: error
      - name: Upload failsafe report
        uses: actions/upload-artifact@v3
        with:
          name: pit-report
          path: tajo-cluster-tests/target/failsafe-reports/
          if-no-files-found: error

